# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 141, 601))
        self.widget.setStyleSheet("QWidget{\n"
"    background-color:qlineargradient(spread:pad, x1:1, y1:0, x2:1, y2:1, stop:0 rgba(250, 202, 14, 255), stop:1 rgba(246, 80, 30, 255))\n"
"}")
        self.widget.setObjectName("widget")
        self.layoutWidget = QtWidgets.QWidget(self.widget)
        self.layoutWidget.setGeometry(QtCore.QRect(6, 20, 131, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_HomePage = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_HomePage.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_HomePage.setStyleSheet("image: url(:/BUttonIcon/Icon/Icon_Home.png);")
        self.pushButton_HomePage.setText("")
        self.pushButton_HomePage.setFlat(True)
        self.pushButton_HomePage.setObjectName("pushButton_HomePage")
        self.verticalLayout.addWidget(self.pushButton_HomePage)
        self.pushButton_UserInterface = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_UserInterface.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_UserInterface.setStyleSheet("image: url(:/BUttonIcon/Icon/Icon_User.png);")
        self.pushButton_UserInterface.setText("")
        self.pushButton_UserInterface.setFlat(True)
        self.pushButton_UserInterface.setObjectName("pushButton_UserInterface")
        self.verticalLayout.addWidget(self.pushButton_UserInterface)
        self.pushButton_Library = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Library.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Library.setStyleSheet("image: url(:/BUttonIcon/Icon/Icon_Library.png);")
        self.pushButton_Library.setText("")
        self.pushButton_Library.setFlat(True)
        self.pushButton_Library.setObjectName("pushButton_Library")
        self.verticalLayout.addWidget(self.pushButton_Library)
        self.pushButton_Settings = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_Settings.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_Settings.setStyleSheet("image: url(:/BUttonIcon/Icon/Icon_Settings.png);")
        self.pushButton_Settings.setText("")
        self.pushButton_Settings.setFlat(True)
        self.pushButton_Settings.setObjectName("pushButton_Settings")
        self.verticalLayout.addWidget(self.pushButton_Settings)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(140, 0, 661, 601))
        self.widget_2.setStyleSheet("QWidget{\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

